name: Flutter build

on: push

permissions:
  actions: read
  contents: read

jobs:
  build:
    name: Build test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: oracle-actions/setup-java@v1
      with:
        release: 19
        version: 19.0.2

    - name: View Java status
      run: java --version

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.10.6
        channel: stable

    - name: View Flutter status
      run: |
        flutter --version
        flutter doctor -v

    - name: Initialize project
      run: |
        flutter create --android-language java --platforms android --project-name mp3_player .
        cp debug/key.properties android/key.properties

    - name: Build APK
      run: flutter build apk -v

    - name: Build App Bundle
      run: flutter build appbundle -v

    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ matrix.os }}
        path: build/app/outputs/
